# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      mysecret:
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#       -  with:
#           my_secret: ${{ inputs.my_secret }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $INPUT_MYSECRET
      - name: Run a one-line script
        run: echo ${{ github.event.inputs.mysecret }}
      - name: VARS
        run: printenv 
