name: CI
on:
  workflow_dispatch:
    inputs:
      mysecret:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FOO: "::add-mask::${{ github.event.inputs.mysecret }}"
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "$FOO"
