name: CI
on:
  workflow_dispatch:
    inputs:
      mysecret:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FOO: ${{ github.event.inputs.mysecret }}
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo $INPUT_MYSECRET
      - name: Run a one-line script
        run: echo ${{ github.event.inputs.mysecret }}
      - name: Run a script
        run: echo
      - name: VARS
        run: printenv 
