name: CI
on:
  workflow_dispatch:
    inputs:
      WEBHOOK_TOKEN:
        required: true
        default: BAR
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      WEBHOOK_TOKEN: "${{ github.event.inputs.WEBHOOK_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "$WEBHOOK_TOKEN"
      - name: Run a one-line script
        run: echo "::add-mask::$WEBHOOK_TOKEN"
