name: CI
on:
  workflow_dispatch:
    inputs:
      FOO:
        required: true
        default: BAR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: jq -r '.inputs.secret' $GITHUB_EVENT_PATH
