name: CI
on:
  workflow_dispatch:
    inputs:
      WEBHOOK_TOKEN:
        required: true
        default: BAR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: cat <(echo "::add-mask::teststring")
